# Generated by Django 3.1 on 2020-08-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockDataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('initial_explicit_input_ports', models.IntegerField()),
                ('initial_implicit_input_ports', models.IntegerField()),
                ('initial_explicit_output_ports', models.IntegerField()),
                ('initial_implicit_output_ports', models.IntegerField()),
                ('initial_control_ports', models.IntegerField()),
                ('initial_command_ports', models.IntegerField()),
                ('initial_display_parameter', models.CharField(max_length=100)),
                ('variable_explicit_input_ports', models.CharField(max_length=100)),
                ('variable_implicit_input_ports', models.CharField(max_length=100)),
                ('variable_explicit_output_ports', models.CharField(max_length=100)),
                ('variable_implicit_output_ports', models.CharField(max_length=100)),
                ('variable_control_ports', models.CharField(max_length=100)),
                ('variable_command_ports', models.CharField(max_length=100)),
                ('variable_display_parameter', models.CharField(max_length=100)),
                ('parameters', models.ManyToManyField(to='xcosblocks.BlockDataType')),
            ],
        ),
    ]
