# Generated by Django 3.1 on 2020-08-06 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xcosblocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='parameters',
        ),
        migrations.AddField(
            model_name='block',
            name='p000',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p000_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p001',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p001_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
    ]
