# Generated by Django 3.1 on 2020-08-06 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xcosblocks', '0002_auto_20200806_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='p002',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p002_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p003',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p003_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p004',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p004_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p005',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p005_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
    ]
