# Generated by Django 3.1 on 2020-08-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcosblocks', '0003_auto_20200806_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='categories',
            field=models.ManyToManyField(to='xcosblocks.Category'),
        ),
    ]
