# Generated by Django 3.1 on 2020-08-06 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xcosblocks', '0005_auto_20200806_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='p006',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p006_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p007',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p007_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p008',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p008_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p009',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p009_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
    ]
