# Generated by Django 3.1 on 2020-08-06 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xcosblocks', '0006_auto_20200806_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='p010',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p010_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p011',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p011_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p012',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p012_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p013',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p013_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p014',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p014_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p015',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p015_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p016',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p016_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p017',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p017_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p018',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p018_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p019',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p019_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p020',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p020_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p021',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p021_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p022',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p022_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p023',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p023_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p024',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p024_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p025',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p025_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p026',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p026_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p027',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p027_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p028',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p028_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p029',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p029_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p030',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p030_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p031',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p031_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p032',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p032_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p033',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p033_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p034',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p034_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p035',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p035_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p036',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p036_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p037',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p037_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p038',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p038_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
        migrations.AddField(
            model_name='block',
            name='p039',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='p039_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockdatatype'),
        ),
    ]
